version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - back
        

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - back

    # Symfony API apache container
    api:
        build: docker/php/
        container_name: api
        ports:
          - 8000:80
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - back

    # Front app for e-commerce
    front:
        build: ./front/
        volumes:
            - ./front:/app
        ports:
            - 3000:3000
            
networks:
    back:

volumes:
    db-data: